import { IBook } from '../pages/mainPage/types';
import { IArtist, IAuthor, IFetchBooks, IFetchDetailBook, IPublisher } from './types';

const mockBooks: IBook[] = [
  {
    uid: 'book18786',
    title: 'Book',
    publishedYear: 2024,
    publishedMonth: 10,
    publishedDay: 8,
    numberOfPages: 30000,
    stardateFrom: null,
    stardateTo: null,
    yearFrom: null,
    yearTo: null,
    novel: true,
    referenceBook: false,
    biographyBook: false,
    rolePlayingBook: false,
    ebook: true,
    anthology: false,
    novelization: false,
    unauthorizedPublication: false,
    audiobook: true,
    audiobookAbridged: false,
    audiobookPublishedYear: 2024,
    audiobookPublishedMonth: 10,
    audiobookPublishedDay: 5,
    audiobookRunTime: 1800,
    productionNumber: null,
  },
];

const mockAuthors: IAuthor[] = [
  {
    uid: 'author',
    name: 'Author',
    birthName: 'Birth',
    gender: 'M',
    dateOfBirth: '1990-08-08',
    placeOfBirth: 'Place',
    dateOfDeath: null,
    placeOfDeath: null,
    artDepartment: true,
    artDirector: false,
    productionDesigner: false,
    cameraAndElectricalDepartment: false,
    cinematographer: false,
    castingDepartment: false,
    costumeDepartment: false,
    costumeDesigner: false,
    director: false,
    assistantOrSecondUnitDirector: false,
    exhibitAndAttractionStaff: false,
    filmEditor: false,
    filmationProductionStaff: false,
    linguist: false,
    locationStaff: false,
    makeupStaff: false,
    merchandiseStaff: false,
    musicDepartment: false,
    composer: false,
    personalAssistant: false,
    producer: false,
    productionAssociate: false,
    productionStaff: false,
    publicationStaff: false,
    scienceConsultant: false,
    soundDepartment: false,
    specialAndVisualEffectsStaff: false,
    author: false,
    audioAuthor: false,
    calendarArtist: false,
    comicArtist: false,
    comicAuthor: false,
    comicColorArtist: false,
    comicCoverArtist: false,
    comicInteriorArtist: false,
    comicInkArtist: false,
    comicPencilArtist: false,
    comicLetterArtist: false,
    comicStripArtist: false,
    gameArtist: false,
    gameAuthor: false,
    novelArtist: false,
    novelAuthor: false,
    referenceArtist: false,
    referenceAuthor: false,
    publicationArtist: false,
    publicationDesigner: false,
    publicationEditor: false,
    publicityArtist: false,
    cbsDigitalStaff: false,
    ilmProductionStaff: false,
    specialFeaturesStaff: false,
    storyEditor: false,
    studioExecutive: false,
    stuntDepartment: false,
    transportationDepartment: false,
    videoGameProductionStaff: false,
    writer: false,
  },
];

const mockArtists: IArtist[] = [
  {
    uid: 'artist1',
    name: 'Artist',
    birthName: 'Birth',
    gender: 'Female',
    dateOfBirth: '1993-11-08',
    placeOfBirth: 'Place',
    dateOfDeath: null,
    placeOfDeath: null,
    artDepartment: true,
    artDirector: false,
    productionDesigner: false,
    cameraAndElectricalDepartment: false,
    cinematographer: false,
    castingDepartment: false,
    costumeDepartment: false,
    costumeDesigner: false,
    director: false,
    assistantOrSecondUnitDirector: false,
    exhibitAndAttractionStaff: false,
    filmEditor: false,
    filmationProductionStaff: false,
    linguist: false,
    locationStaff: false,
    makeupStaff: false,
    merchandiseStaff: false,
    musicDepartment: false,
    composer: false,
    personalAssistant: false,
    producer: false,
    productionAssociate: false,
    productionStaff: false,
    publicationStaff: false,
    scienceConsultant: false,
    soundDepartment: false,
    specialAndVisualEffectsStaff: false,
    author: false,
    audioAuthor: false,
    calendarArtist: false,
    comicArtist: false,
    comicAuthor: false,
    comicColorArtist: false,
    comicCoverArtist: false,
    comicInteriorArtist: false,
    comicInkArtist: false,
    comicPencilArtist: false,
    comicLetterArtist: false,
    comicStripArtist: false,
    gameArtist: false,
    gameAuthor: false,
    novelArtist: false,
    novelAuthor: false,
    referenceArtist: false,
    referenceAuthor: false,
    publicationArtist: false,
    publicationDesigner: false,
    publicationEditor: false,
    publicityArtist: false,
    cbsDigitalStaff: false,
    ilmProductionStaff: false,
    specialFeaturesStaff: false,
    storyEditor: false,
    studioExecutive: false,
    stuntDepartment: false,
    transportationDepartment: false,
    videoGameProductionStaff: false,
    writer: false,
  },
];

const mockPublishers: IPublisher[] = [
  {
    uid: 'publisher1',
    name: 'Publisher',
    broadcaster: false,
    streamingService: false,
    collectibleCompany: false,
    conglomerate: false,
    visualEffectsCompany: false,
    digitalVisualEffectsCompany: false,
    distributor: false,
    gameCompany: false,
    filmEquipmentCompany: false,
    makeUpEffectsStudio: false,
    mattePaintingCompany: false,
    modelAndMiniatureEffectsCompany: false,
    postProductionCompany: false,
    productionCompany: true,
    propCompany: false,
    recordLabel: false,
    specialEffectsCompany: false,
    tvAndFilmProductionCompany: false,
    videoGameCompany: false,
    publisher: true,
    publicationArtStudio: false,
  },
];

export const mockFetchDetailBook: IFetchDetailBook = {
  book: {
    uid: 'book',
    title: 'Book',
    authors: mockAuthors,
    artists: mockArtists,
    editors: [],
    audiobookNarrators: [],
    publishers: mockPublishers,
    audiobookPublishers: [],
    characters: [],
    references: [],
    audiobookReferences: [],
    bookCollections: [],
    bookSeries: [{ uid: 'series56', name: 'Series' }],
    publishedYear: 2023,
    publishedMonth: 1,
    publishedDay: 15,
    numberOfPages: 300,
    stardateFrom: null,
    stardateTo: null,
    yearFrom: null,
    yearTo: null,
    novel: true,
    referenceBook: false,
    biographyBook: false,
    rolePlayingBook: false,
    ebook: true,
    anthology: false,
    novelization: false,
    unauthorizedPublication: false,
    audiobook: true,
    audiobookAbridged: false,
    audiobookPublishedYear: 2023,
    audiobookPublishedMonth: 1,
    audiobookPublishedDay: 15,
    audiobookRunTime: 180,
    productionNumber: null,
  },
};

export const mockFetchBooks: IFetchBooks = {
  bookList: [
    {
      uid: 'book',
      title: 'Book',
      publishedYear: 2023,
      publishedMonth: 1,
      publishedDay: 15,
      numberOfPages: 300,
      stardateFrom: null,
      stardateTo: null,
      yearFrom: null,
      yearTo: null,
      novel: true,
      referenceBook: false,
      biographyBook: false,
      rolePlayingBook: false,
      ebook: true,
      anthology: false,
      novelization: false,
      unauthorizedPublication: false,
      audiobook: true,
      audiobookAbridged: false,
      audiobookPublishedYear: 2024,
      audiobookPublishedMonth: 10,
      audiobookPublishedDay: 11,
      audiobookRunTime: 888888,
      productionNumber: null,
    },
  ],
  totalElements: mockBooks.length,
};
